version: "3.9"
services:
  jsdoop-server:
    restart: always
    build: .
    ports:
      - "8081:8081"
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external:
      name: jsdoop_network
